import { poppins, roboto } from "@/font";
import clsx from "clsx";
import "./globals.css";
import { Navbar } from "@/components/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className={clsx(poppins.variable, roboto.variable)}>
      <body className="font-poppins">
        <section>
          <div className="flex min-h-screen flex-col p-8">
            <Navbar />
            <main>{children}</main>
            <div>Footer</div>
          </div>
        </section>
      </body>
    </html>
  );
}
