import "./globals.css";
import { poppins, roboto } from "@/font";
import { Navbar } from "@/components/Navbar/Navbar";
import { Footer } from "@/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${roboto.variable}`}>
      <body className="font-poppins bg-slate-100">
        <section>
          <Navbar />
          <div className="border-t border-[#bbbaba] opacity-30" />

          <div className="flex h-auto flex-col pt-4 pb-12 px-20 bg-white">
            <main>{children}</main>
          </div>

          <div className="border-t border-[#bbbaba] opacity-30" />
          <Footer />
        </section>
      </body>
    </html>
  );
}
